# Created by: mallocbsd <mallocbsd@foxmail.com>
# $FreeBSD$

PORTNAME=	iscsictl

MAIN_SRC=	usr.bin/${PORTNAME}
EXTRA_SRCS=	sys/dev/iscsi
MAN_FILES=	man/man8/${PORTNAME}.8 man/man5/iscsi.conf.5

.include "${.CURDIR}/../mfc-ls/Makefile"
