--- bin/ps/keyword.c.orig	2015-12-29 09:01:39 UTC
+++ bin/ps/keyword.c
@@ -47,6 +47,7 @@ __FBSDID("$FreeBSD: releng/10.1/bin/ps/k
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
+#include <libxo/xo.h>
 
 #include "ps.h"
 
@@ -64,115 +65,170 @@ static int  vcmp(const void *, const voi
 
 /* PLEASE KEEP THE TABLE BELOW SORTED ALPHABETICALLY!!! */
 static VAR var[] = {
-	{"%cpu", "%CPU", NULL, 0, pcpu, 0, CHAR, NULL, 0},
-	{"%mem", "%MEM", NULL, 0, pmem, 0, CHAR, NULL, 0},
-	{"acflag", "ACFLG", NULL, 0, kvar, KOFF(ki_acflag), USHORT, "x", 0},
-	{"acflg", "", "acflag", 0, NULL, 0, CHAR, NULL, 0},
-	{"args", "COMMAND", NULL, COMM|LJUST|USER, arguments, 0,
-		CHAR, NULL, 0},
-	{"blocked", "", "sigmask", 0, NULL, 0, CHAR, NULL, 0},
-	{"caught", "", "sigcatch", 0, NULL, 0, CHAR, NULL, 0},
-	{"class", "CLASS", NULL, LJUST, loginclass, 0, CHAR, NULL, 0},
-	{"comm", "COMMAND", NULL, LJUST, ucomm, 0, CHAR, NULL, 0},
-	{"command", "COMMAND", NULL, COMM|LJUST|USER, command, 0,
-		CHAR, NULL, 0},
-	{"cow", "COW", NULL, 0, kvar, KOFF(ki_cow), UINT, "u", 0},
-	{"cpu", "CPU", NULL, 0, kvar, KOFF(ki_estcpu), UINT, "d", 0},
-	{"cputime", "", "time", 0, NULL, 0, CHAR, NULL, 0},
-	{"dsiz", "DSIZ", NULL, 0, kvar, KOFF(ki_dsize), PGTOK, "ld", 0},
-	{"egid", "", "gid", 0, NULL, 0, CHAR, NULL, 0},
-	{"egroup", "", "group", 0, NULL, 0, CHAR, NULL, 0},
-	{"emul", "EMUL", NULL, LJUST, emulname, 0, CHAR, NULL, 0},
-	{"etime", "ELAPSED", NULL, USER, elapsed, 0, CHAR, NULL, 0},
-	{"etimes", "ELAPSED", NULL, USER, elapseds, 0, CHAR, NULL, 0},
-	{"euid", "", "uid", 0, NULL, 0, CHAR, NULL, 0},
-	{"f", "F", NULL, 0, kvar, KOFF(ki_flag), INT, "x", 0},
-	{"f2", "F2", NULL, 0, kvar, KOFF(ki_flag2), INT, "08x", 0},
-	{"fib", "FIB", NULL, 0, kvar, KOFF(ki_fibnum), INT, "d", 0},
-	{"flags", "", "f", 0, NULL, 0, CHAR, NULL, 0},
-	{"flags2", "", "f2", 0, NULL, 0, CHAR, NULL, 0},
-	{"gid", "GID", NULL, 0, kvar, KOFF(ki_groups), UINT, UIDFMT, 0},
-	{"group", "GROUP", NULL, LJUST, egroupname, 0, CHAR, NULL, 0},
-	{"ignored", "", "sigignore", 0, NULL, 0, CHAR, NULL, 0},
-	{"inblk", "INBLK", NULL, USER, rvar, ROFF(ru_inblock), LONG, "ld", 0},
-	{"inblock", "", "inblk", 0, NULL, 0, CHAR, NULL, 0},
-	{"jid", "JID", NULL, 0, kvar, KOFF(ki_jid), INT, "d", 0},
-	{"jobc", "JOBC", NULL, 0, kvar, KOFF(ki_jobc), SHORT, "d", 0},
-	{"ktrace", "KTRACE", NULL, 0, kvar, KOFF(ki_traceflag), INT, "x", 0},
-	{"label", "LABEL", NULL, LJUST, label, 0, CHAR, NULL, 0},
-	{"lim", "LIM", NULL, 0, maxrss, 0, CHAR, NULL, 0},
-	{"lockname", "LOCK", NULL, LJUST, lockname, 0, CHAR, NULL, 0},
-	{"login", "LOGIN", NULL, LJUST, logname, 0, CHAR, NULL, 0},
-	{"logname", "", "login", 0, NULL, 0, CHAR, NULL, 0},
-	{"lstart", "STARTED", NULL, LJUST|USER, lstarted, 0, CHAR, NULL, 0},
-	{"lwp", "LWP", NULL, 0, kvar, KOFF(ki_tid), UINT, LWPFMT, 0},
-	{"majflt", "MAJFLT", NULL, USER, rvar, ROFF(ru_majflt), LONG, "ld", 0},
-	{"minflt", "MINFLT", NULL, USER, rvar, ROFF(ru_minflt), LONG, "ld", 0},
-	{"msgrcv", "MSGRCV", NULL, USER, rvar, ROFF(ru_msgrcv), LONG, "ld", 0},
-	{"msgsnd", "MSGSND", NULL, USER, rvar, ROFF(ru_msgsnd), LONG, "ld", 0},
-	{"mwchan", "MWCHAN", NULL, LJUST, mwchan, 0, CHAR, NULL, 0},
-	{"ni", "", "nice", 0, NULL, 0, CHAR, NULL, 0},
-	{"nice", "NI", NULL, 0, kvar, KOFF(ki_nice), CHAR, "d", 0},
-	{"nivcsw", "NIVCSW", NULL, USER, rvar, ROFF(ru_nivcsw), LONG, "ld", 0},
-	{"nlwp", "NLWP", NULL, 0, kvar, KOFF(ki_numthreads), UINT, NLWPFMT, 0},
-	{"nsignals", "", "nsigs", 0, NULL, 0, CHAR, NULL, 0},
-	{"nsigs", "NSIGS", NULL, USER, rvar, ROFF(ru_nsignals), LONG, "ld", 0},
-	{"nswap", "NSWAP", NULL, USER, rvar, ROFF(ru_nswap), LONG, "ld", 0},
-	{"nvcsw", "NVCSW", NULL, USER, rvar, ROFF(ru_nvcsw), LONG, "ld", 0},
-	{"nwchan", "NWCHAN", NULL, LJUST, nwchan, 0, CHAR, NULL, 0},
-	{"oublk", "OUBLK", NULL, USER, rvar, ROFF(ru_oublock), LONG, "ld", 0},
-	{"oublock", "", "oublk", 0, NULL, 0, CHAR, NULL, 0},
-	{"paddr", "PADDR", NULL, 0, kvar, KOFF(ki_paddr), KPTR, "lx", 0},
-	{"pagein", "PAGEIN", NULL, USER, pagein, 0, CHAR, NULL, 0},
-	{"pcpu", "", "%cpu", 0, NULL, 0, CHAR, NULL, 0},
-	{"pending", "", "sig", 0, NULL, 0, CHAR, NULL, 0},
-	{"pgid", "PGID", NULL, 0, kvar, KOFF(ki_pgid), UINT, PIDFMT, 0},
-	{"pid", "PID", NULL, 0, kvar, KOFF(ki_pid), UINT, PIDFMT, 0},
-	{"pmem", "", "%mem", 0, NULL, 0, CHAR, NULL, 0},
-	{"ppid", "PPID", NULL, 0, kvar, KOFF(ki_ppid), UINT, PIDFMT, 0},
-	{"pri", "PRI", NULL, 0, pri, 0, CHAR, NULL, 0},
-	{"re", "RE", NULL, INF127, kvar, KOFF(ki_swtime), UINT, "d", 0},
-	{"rgid", "RGID", NULL, 0, kvar, KOFF(ki_rgid), UINT, UIDFMT, 0},
-	{"rgroup", "RGROUP", NULL, LJUST, rgroupname, 0, CHAR, NULL, 0},
-	{"rss", "RSS", NULL, 0, kvar, KOFF(ki_rssize), PGTOK, "ld", 0},
-	{"rtprio", "RTPRIO", NULL, 0, priorityr, KOFF(ki_pri), CHAR, NULL, 0},
-	{"ruid", "RUID", NULL, 0, kvar, KOFF(ki_ruid), UINT, UIDFMT, 0},
-	{"ruser", "RUSER", NULL, LJUST, runame, 0, CHAR, NULL, 0},
-	{"sid", "SID", NULL, 0, kvar, KOFF(ki_sid), UINT, PIDFMT, 0},
-	{"sig", "PENDING", NULL, 0, kvar, KOFF(ki_siglist), INT, "x", 0},
-	{"sigcatch", "CAUGHT", NULL, 0, kvar, KOFF(ki_sigcatch), UINT, "x", 0},
-	{"sigignore", "IGNORED", NULL, 0, kvar, KOFF(ki_sigignore),
-		UINT, "x", 0},
-	{"sigmask", "BLOCKED", NULL, 0, kvar, KOFF(ki_sigmask), UINT, "x", 0},
-	{"sl", "SL", NULL, INF127, kvar, KOFF(ki_slptime), UINT, "d", 0},
-	{"ssiz", "SSIZ", NULL, 0, kvar, KOFF(ki_ssize), PGTOK, "ld", 0},
-	{"start", "STARTED", NULL, LJUST|USER, started, 0, CHAR, NULL, 0},
-	{"stat", "", "state", 0, NULL, 0, CHAR, NULL, 0},
-	{"state", "STAT", NULL, LJUST, state, 0, CHAR, NULL, 0},
-	{"svgid", "SVGID", NULL, 0, kvar, KOFF(ki_svgid), UINT, UIDFMT, 0},
-	{"svuid", "SVUID", NULL, 0, kvar, KOFF(ki_svuid), UINT, UIDFMT, 0},
-	{"systime", "SYSTIME", NULL, USER, systime, 0, CHAR, NULL, 0},
-	{"tdaddr", "TDADDR", NULL, 0, kvar, KOFF(ki_tdaddr), KPTR, "lx", 0},
-	{"tdev", "TDEV", NULL, 0, tdev, 0, CHAR, NULL, 0},
-	{"tdnam", "TDNAM", NULL, LJUST, tdnam, 0, CHAR, NULL, 0},
-	{"time", "TIME", NULL, USER, cputime, 0, CHAR, NULL, 0},
-	{"tpgid", "TPGID", NULL, 0, kvar, KOFF(ki_tpgid), UINT, PIDFMT, 0},
-	{"tsid", "TSID", NULL, 0, kvar, KOFF(ki_tsid), UINT, PIDFMT, 0},
-	{"tsiz", "TSIZ", NULL, 0, kvar, KOFF(ki_tsize), PGTOK, "ld", 0},
-	{"tt", "TT ", NULL, 0, tname, 0, CHAR, NULL, 0},
-	{"tty", "TTY", NULL, LJUST, longtname, 0, CHAR, NULL, 0},
-	{"ucomm", "UCOMM", NULL, LJUST, ucomm, 0, CHAR, NULL, 0},
-	{"uid", "UID", NULL, 0, kvar, KOFF(ki_uid), UINT, UIDFMT, 0},
-	{"upr", "UPR", NULL, 0, upr, 0, CHAR, NULL, 0},
-	{"uprocp", "UPROCP", NULL, 0, kvar, KOFF(ki_paddr), KPTR, "lx", 0},
-	{"user", "USER", NULL, LJUST, uname, 0, CHAR, NULL, 0},
-	{"usertime", "USERTIME", NULL, USER, usertime, 0, CHAR, NULL, 0},
-	{"usrpri", "", "upr", 0, NULL, 0, CHAR, NULL, 0},
-	{"vsize", "", "vsz", 0, NULL, 0, CHAR, NULL, 0},
-	{"vsz", "VSZ", NULL, 0, vsize, 0, CHAR, NULL, 0},
-	{"wchan", "WCHAN", NULL, LJUST, wchan, 0, CHAR, NULL, 0},
-	{"xstat", "XSTAT", NULL, 0, kvar, KOFF(ki_xstat), USHORT, "x", 0},
-	{"", NULL, NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"%cpu", "%CPU", NULL, "percent-cpu", 0, pcpu, 0, CHAR, NULL, 0},
+	{"%mem", "%MEM", NULL, "percent-memory", 0, pmem, 0, CHAR, NULL, 0},
+	{"acflag", "ACFLG", NULL, "accounting-flag", 0, kvar, KOFF(ki_acflag),
+	    USHORT, "x", 0},
+	{"acflg", "", "acflag", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"args", "COMMAND", NULL, "arguments", COMM|LJUST|USER, arguments, 0,
+	    CHAR, NULL, 0},
+	{"blocked", "", "sigmask", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"caught", "", "sigcatch", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"class", "CLASS", NULL, "login-class", LJUST, loginclass, 0, CHAR,
+	    NULL, 0},
+	{"comm", "COMMAND", NULL, "command", LJUST, ucomm, 0, CHAR, NULL, 0},
+	{"command", "COMMAND", NULL, "command", COMM|LJUST|USER, command, 0,
+	    CHAR, NULL, 0},
+	{"cow", "COW", NULL, "copy-on-write-faults", 0, kvar, KOFF(ki_cow),
+	    UINT, "u", 0},
+	{"cpu", "CPU", NULL, "cpu-usage", 0, kvar, KOFF(ki_estcpu), UINT, "d",
+	    0},
+	{"cputime", "", "time", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"dsiz", "DSIZ", NULL, "data-size", 0, kvar, KOFF(ki_dsize), PGTOK,
+	    "ld", 0},
+	{"egid", "", "gid", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"egroup", "", "group", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"emul", "EMUL", NULL, "emulation-envirnment", LJUST, emulname, 0,
+	    CHAR, NULL, 0},
+	{"etime", "ELAPSED", NULL, "elapsed-time", USER, elapsed, 0, CHAR,
+	    NULL, 0},
+	{"etimes", "ELAPSED", NULL, "elapsed-times", USER, elapseds, 0, CHAR,
+	    NULL, 0},
+	{"euid", "", "uid", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"f", "F", NULL, "flags", 0, kvar, KOFF(ki_flag), INT, "x", 0},
+	{"f2", "F2", NULL, "flags2", 0, kvar, KOFF(ki_flag2), INT, "08x", 0},
+	{"fib", "FIB", NULL, "fib", 0, kvar, KOFF(ki_fibnum), INT, "d", 0},
+	{"flags", "", "f", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"flags2", "", "f2", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"gid", "GID", NULL, "gid", 0, kvar, KOFF(ki_groups), UINT, UIDFMT, 0},
+	{"group", "GROUP", NULL, "group", LJUST, egroupname, 0, CHAR, NULL, 0},
+	{"ignored", "", "sigignore", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"inblk", "INBLK", NULL, "read-blocks", USER, rvar, ROFF(ru_inblock),
+	    LONG, "ld", 0},
+	{"inblock", "", "inblk", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"jid", "JID", NULL, "jail-id", 0, kvar, KOFF(ki_jid), INT, "d", 0},
+	{"jobc", "JOBC", NULL, "job-control-count", 0, kvar, KOFF(ki_jobc),
+	    SHORT, "d", 0},
+	{"ktrace", "KTRACE", NULL, "ktrace", 0, kvar, KOFF(ki_traceflag), INT,
+	    "x", 0},
+	{"label", "LABEL", NULL, "label", LJUST, label, 0, CHAR, NULL, 0},
+	{"lim", "LIM", NULL, "memory-limit", 0, maxrss, 0, CHAR, NULL, 0},
+	{"lockname", "LOCK", NULL, "lock-name", LJUST, lockname, 0, CHAR, NULL,
+	    0},
+	{"login", "LOGIN", NULL, "login-name", LJUST, logname, 0, CHAR, NULL,
+	    0},
+	{"logname", "", "login", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"lstart", "STARTED", NULL, "start-time", LJUST|USER, lstarted, 0,
+	    CHAR, NULL, 0},
+	{"lwp", "LWP", NULL, "process-thread-id", 0, kvar, KOFF(ki_tid), UINT,
+	    LWPFMT, 0},
+	{"majflt", "MAJFLT", NULL, "major-faults", USER, rvar, ROFF(ru_majflt),
+	    LONG, "ld", 0},
+	{"minflt", "MINFLT", NULL, "minor-faults", USER, rvar, ROFF(ru_minflt),
+	    LONG, "ld", 0},
+	{"msgrcv", "MSGRCV", NULL, "received-messages", USER, rvar,
+	    ROFF(ru_msgrcv), LONG, "ld", 0},
+	{"msgsnd", "MSGSND", NULL, "sent-messages", USER, rvar,
+	    ROFF(ru_msgsnd), LONG, "ld", 0},
+	{"mwchan", "MWCHAN", NULL, "wait-channel", LJUST, mwchan, 0, CHAR,
+	    NULL, 0},
+	{"ni", "", "nice", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"nice", "NI", NULL, "nice", 0, kvar, KOFF(ki_nice), CHAR, "d", 0},
+	{"nivcsw", "NIVCSW", NULL, "involuntary-context-switches", USER, rvar,
+	    ROFF(ru_nivcsw), LONG, "ld", 0},
+	{"nlwp", "NLWP", NULL, "threads", 0, kvar, KOFF(ki_numthreads), UINT,
+	    NLWPFMT, 0},
+	{"nsignals", "", "nsigs", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"nsigs", "NSIGS", NULL, "signals-taken", USER, rvar,
+	    ROFF(ru_nsignals), LONG, "ld", 0},
+	{"nswap", "NSWAP", NULL, "swaps", USER, rvar, ROFF(ru_nswap), LONG,
+	    "ld", 0},
+	{"nvcsw", "NVCSW", NULL, "voluntary-context-switches", USER, rvar,
+	    ROFF(ru_nvcsw), LONG, "ld", 0},
+	{"nwchan", "NWCHAN", NULL, "wait-channel-address", LJUST, nwchan, 0,
+	    CHAR, NULL, 0},
+	{"oublk", "OUBLK", NULL, "written-blocks", USER, rvar,
+	    ROFF(ru_oublock), LONG, "ld", 0},
+	{"oublock", "", "oublk", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"paddr", "PADDR", NULL, "process-address", 0, kvar, KOFF(ki_paddr),
+	    KPTR, "lx", 0},
+	{"pagein", "PAGEIN", NULL, "pageins", USER, pagein, 0, CHAR, NULL, 0},
+	{"pcpu", "", "%cpu", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"pending", "", "sig", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"pgid", "PGID", NULL, "process-group", 0, kvar, KOFF(ki_pgid), UINT,
+	    PIDFMT, 0},
+	{"pid", "PID", NULL, "pid", 0, kvar, KOFF(ki_pid), UINT, PIDFMT, 0},
+	{"pmem", "", "%mem", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"ppid", "PPID", NULL, "ppid", 0, kvar, KOFF(ki_ppid), UINT, PIDFMT, 0},
+	{"pri", "PRI", NULL, "priority", 0, pri, 0, CHAR, NULL, 0},
+	{"re", "RE", NULL, "residency-time", INF127, kvar, KOFF(ki_swtime),
+	    UINT, "d", 0},
+	{"rgid", "RGID", NULL, "real-gid", 0, kvar, KOFF(ki_rgid), UINT,
+	    UIDFMT, 0},
+	{"rgroup", "RGROUP", NULL, "real-group", LJUST, rgroupname, 0, CHAR,
+	    NULL, 0},
+	{"rss", "RSS", NULL, "rss", 0, kvar, KOFF(ki_rssize), PGTOK, "ld", 0},
+	{"rtprio", "RTPRIO", NULL, "realtime-priority", 0, priorityr,
+	    KOFF(ki_pri), CHAR, NULL, 0},
+	{"ruid", "RUID", NULL, "real-uid", 0, kvar, KOFF(ki_ruid), UINT,
+	    UIDFMT, 0},
+	{"ruser", "RUSER", NULL, "real-user", LJUST, runame, 0, CHAR, NULL, 0},
+	{"sid", "SID", NULL, "sid", 0, kvar, KOFF(ki_sid), UINT, PIDFMT, 0},
+	{"sig", "PENDING", NULL, "signals-pending", 0, kvar, KOFF(ki_siglist),
+	    INT, "x", 0},
+	{"sigcatch", "CAUGHT", NULL, "signals-caught", 0, kvar,
+	    KOFF(ki_sigcatch), UINT, "x", 0},
+	{"sigignore", "IGNORED", NULL, "signals-ignored", 0, kvar,
+	    KOFF(ki_sigignore), UINT, "x", 0},
+	{"sigmask", "BLOCKED", NULL, "signal-mask", 0, kvar, KOFF(ki_sigmask),
+	    UINT, "x", 0},
+	{"sl", "SL", NULL, "sleep-time", INF127, kvar, KOFF(ki_slptime), UINT,
+	    "d", 0},
+	{"ssiz", "SSIZ", NULL, "stack-size", 0, kvar, KOFF(ki_ssize), PGTOK,
+	    "ld", 0},
+	{"start", "STARTED", NULL, "start-time", LJUST|USER, started, 0, CHAR,
+	    NULL, 0},
+	{"stat", "", "state", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"state", "STAT", NULL, "state", LJUST, state, 0, CHAR, NULL, 0},
+	{"svgid", "SVGID", NULL, "saved-gid", 0, kvar, KOFF(ki_svgid), UINT,
+	    UIDFMT, 0},
+	{"svuid", "SVUID", NULL, "saved-uid", 0, kvar, KOFF(ki_svuid), UINT,
+	    UIDFMT, 0},
+	{"systime", "SYSTIME", NULL, "system-time", USER, systime, 0, CHAR,
+	    NULL, 0},
+	{"tdaddr", "TDADDR", NULL, "thread-address", 0, kvar, KOFF(ki_tdaddr),
+	    KPTR, "lx", 0},
+	{"tdev", "TDEV", NULL, "terminal-device", 0, tdev, 0, CHAR, NULL, 0},
+	{"tdnam", "TDNAM", NULL, "terminal-device-name", LJUST, tdnam, 0, CHAR,
+	    NULL, 0},
+	{"time", "TIME", NULL, "cpu-time", USER, cputime, 0, CHAR, NULL, 0},
+	{"tpgid", "TPGID", NULL, "terminal-process-gid", 0, kvar,
+	    KOFF(ki_tpgid), UINT, PIDFMT, 0},
+	/*{"tracer", "TRACER", NULL, "tracer", 0, kvar, KOFF(ki_tracer), UINT,
+	    PIDFMT, 0},*/
+	{"tsid", "TSID", NULL, "terminal-sid", 0, kvar, KOFF(ki_tsid), UINT,
+	    PIDFMT, 0},
+	{"tsiz", "TSIZ", NULL, "text-size", 0, kvar, KOFF(ki_tsize), PGTOK,
+	    "ld", 0},
+	{"tt", "TT ", NULL, "terminal-name", 0, tname, 0, CHAR, NULL, 0},
+	{"tty", "TTY", NULL, "tty", LJUST, longtname, 0, CHAR, NULL, 0},
+	{"ucomm", "UCOMM", NULL, "accounting-name", LJUST, ucomm, 0, CHAR,
+	    NULL, 0},
+	{"uid", "UID", NULL, "uid", 0, kvar, KOFF(ki_uid), UINT, UIDFMT, 0},
+	{"upr", "UPR", NULL, "user-priority", 0, upr, 0, CHAR, NULL, 0},
+	{"uprocp", "UPROCP", NULL, "process-address", 0, kvar, KOFF(ki_paddr),
+	    KPTR, "lx", 0},
+	{"user", "USER", NULL, "user", LJUST, uname, 0, CHAR, NULL, 0},
+	{"usertime", "USERTIME", NULL, "user-time", USER, usertime, 0, CHAR,
+	    NULL, 0},
+	{"usrpri", "", "upr", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"vsize", "", "vsz", NULL, 0, NULL, 0, CHAR, NULL, 0},
+	{"vsz", "VSZ", NULL, "virtual-size", 0, vsize, 0, CHAR, NULL, 0},
+	{"wchan", "WCHAN", NULL, "wait-channel", LJUST, wchan, 0, CHAR, NULL,
+	    0},
+	{"xstat", "XSTAT", NULL, "exit-status", 0, kvar, KOFF(ki_xstat),
+	    USHORT, "x", 0},
+	{"", NULL, NULL, NULL, 0, NULL, 0, CHAR, NULL, 0},
 };
 
 void
@@ -184,16 +240,19 @@ showkey(void)
 
 	i = 0;
 	sep = "";
+	xo_open_list("key");
 	for (v = var; *(p = v->name); ++v) {
 		int len = strlen(p);
 		if (termwidth && (i += len + 1) > termwidth) {
 			i = len;
 			sep = "\n";
 		}
-		(void) printf("%s%s", sep, p);
+		xo_emit("{P:/%s}{l:key/%s}", sep, p);
 		sep = " ";
 	}
-	(void) printf("\n");
+	xo_emit("\n");
+	xo_close_list("key");
+	xo_finish();
 }
 
 void
